Repository thelokeshgoel00/Competitive_Programming, pull requests merged in 2020-10, with the labels that each got.

#91 Party Schedule (https://www.spoj.com/problems/PARTY/)
  SPOJ/partyDp.cpp
Labels: hacktoberfest-accepted

#90 HacherEarth questions
  HackerEarth/Sehwag And ETF.cpp
  HackerEarth/innocent swaps and its emotions.cpp
Labels: hacktoberfest-accepted

#89 SPOJ questinos
  SPOJ/CSQUARE.cpp
  SPOJ/DCEPC11B.cpp
  SPOJ/GCDEX.cpp
Labels: hacktoberfest-accepted

#88 FINXOR
  CodeChef/ADAMAT.cpp
  CodeChef/CHFNSWAP.cpp
  CodeChef/COVID19B.cpp
  CodeChef/CRDGAME2.cpp
  CodeChef/FINXOR.cpp
  CodeChef/TREE2.cpp
Labels: hacktoberfest-accepted

#87 Update find-factorial.cpp
  HackerEarth/find-factorial.cpp
Labels: enhancement, hacktoberfest-accepted

#85 C lang problems
  Hackerrank/DigitFrequency.c
  Hackerrank/PrintingTokens.c
Labels: hacktoberfest-accepted

#84 Codeforces Soln added
  CodeForces/CF1419C.cpp
  CodeForces/CF1419D2.cpp
  CodeForces/CF166E.cpp
  CodeForces/CF893C.cpp
Labels: hacktoberfest-accepted

#83 Interviewbit math
  Interviewbit/DynamicProgramming/Intersecting Chords in a Circle
  Interviewbit/DynamicProgramming/Jump Game Array
  Interviewbit/DynamicProgramming/Largest area of rectangle with permutations
  Interviewbit/DynamicProgramming/Length of Longest Subsequence
  Interviewbit/DynamicProgramming/Longest Arithmetic Progression
  Interviewbit/DynamicProgramming/Max Sum Without Adjacent Elements
  Interviewbit/DynamicProgramming/Min jumps array
  Interviewbit/DynamicProgramming/N digit numbers with digit sum S
  Interviewbit/DynamicProgramming/Stairs
  Interviewbit/DynamicProgramming/Ways to decode
  Interviewbit/Math/Excel Coloumn Title
  Interviewbit/Math/Excel Column Number
  Interviewbit/Math/FizzBuzz
  Interviewbit/Math/Greatest Common Divisor
  Interviewbit/Math/Grid Unique Paths
  Interviewbit/Math/Largest Coprime Divisor
  Interviewbit/Math/Palindrome Integer
  Interviewbit/Math/Power of two integers
  Interviewbit/Math/Prime Sum
  Interviewbit/Math/Rearrange array
  Interviewbit/Math/Reverse Integer
  Interviewbit/Math/Sum of pairwise hamming distance
  Interviewbit/Math/Trailing Zeroes in Factorial
Labels: hacktoberfest-accepted

#94 Added some solutions
  CODECHEF/BOJACK.cpp
  CODECHEF/CHEFCAKE.cpp
  CODECHEF/CHEFCOMP.cpp
  CODECHEF/CHEFNSWAP.cpp
  CODECHEF/FIRESC.cpp
  CODECHEF/ORTHODOX.cpp
  CODECHEF/XORCIST.cpp
  CodeForces/CF118E.cpp
  CodeForces/CF1342C.cpp
  CodeForces/CF659C.cpp
  Hackerearth/feasible relation.cpp
  Hackerearth/he_bishu and gf.cpp
  Hackerearth/monk and island.cpp
  Hackerrank/even tree.cpp
  Hackerrank/journey to the moon hackerrank.cpp
  Hackerrank/road and library.cpp
  Miscellaneous/counting room cses.cpp
  Miscellaneous/covid cc.cpp
  Miscellaneous/jungle run.cpp
  Miscellaneous/shotest range.cpp
  SPOJ/submerge.cpp
Labels: hacktoberfest-accepted, help wanted

#95 Python problem
  Hackerrank/List_Comprehensions.py
  Hackerrank/Print_function.py
Labels: hacktoberfest-accepted

#97 hactoberfest
  TEMPLATE.cpp
Labels: hacktoberfest-accepted

#99 hactoberfest
  CEOI/tower.cpp
Labels: hacktoberfest-accepted

#100 Utopian Tree
  Hackerrank/UtopianTree.c
Labels: hacktoberfest-accepted

#103 CF1385B
  CodeForces/CF1385B.cpp
Labels: hacktoberfest-accepted

#108 added leetcode,CODECHEF, SPOJ, and GFG DP questions
  CodeChef/FROGV.cpp
  CodeChef/SUBINC.cpp
  GeeksForGeeks/LCS_of_3_strings.cpp
  GeeksForGeeks/count_no_of_hops(order  matters).cpp
  GeeksForGeeks/form_a_palindrome.cpp
  GeeksForGeeks/max_sum-bitonic_subsequence.cpp
  GeeksForGeeks/maximize_cut_segments.cpp
  GeeksForGeeks/minimum_no_coin.cpp
  GeeksForGeeks/minimum_sum_partition.cpp
  GeeksForGeeks/nCr.cpp
  GeeksForGeeks/reach_a_given_score.cpp
  GeeksForGeeks/rod_cutting.cpp
  GeeksForGeeks/shortest_commmon_supersequence.cpp
  GeeksForGeeks/string_subsequence(count LCS).cpp
  LeetCode/(snap_sack_DP)coin_change.cpp
  LeetCode/Hamming dist.cpp
  LeetCode/LIS.cpp
  LeetCode/Queue_Reconstruction_by_Height.cpp
  LeetCode/coin_change_2.cpp
  LeetCode/good-leafs.cpp
  LeetCode/kbit.cpp
  LeetCode/largest_divisible_subset.cpp
  LeetCode/sub-arr.cpp
  LeetCode/two_city_scheduling.cpp
  LeetCode/ugly_no_2.cpp
  SPOJ/(big_numbers)JULKA_spoj.cpp
  SPOJ/BUGLIFE.cpp
  SPOJ/FCTRL2_spoj.cpp
  SPOJ/FIBOSUM.cpp
  SPOJ/MAXSUMSU_spoj.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#107 HackerRank Python Problems -- Basic Data Types
  Hackerrank/Python/Basic Data Types/findTheSecondLargestNumber.py
  Hackerrank/Python/Basic Data Types/findingThePercentage.py
  Hackerrank/Python/Basic Data Types/listComprehensions.py
  Hackerrank/Python/Basic Data Types/lists.py
  Hackerrank/Python/Basic Data Types/nestedList.py
  Hackerrank/Python/Basic Data Types/tuples.py
Labels: hacktoberfest-accepted

#106 hacktoberfest
  GeeksForGeeks/max-and-second-max.cpp
Labels: hacktoberfest-accepted

#110 hacktoberfest
  HackerEarth/find-factorial.cpp
Labels: hacktoberfest-accepted

#123 Add `Cheating A Boolean Tree` Kattis `C` solution
  Kattis/cheatingbooleantree.c
Labels: enhancement, good first issue, hacktoberfest-accepted

#121 Find a string
  Hackerrank/Python/Basic Data Types/findAString.py
Labels: hacktoberfest-accepted

#119 Adding solution for problem 1601 - hacktoberfest
  LeetCode/maximum_number_of_achievable_transfer_requests.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#117 Adding solution for problem 207 - hacktoberfest
  LeetCode/CourseSchedule.java
Labels: hacktoberfest-accepted

#116 Adding solution for problem 41 in python - hacktoberfest
  LeetCode/first_missing_positive.py
Labels: hacktoberfest-accepted

#115 Added Code for Compress the string
  Hackerrank/Python/Basic Data Types/compressString.py
Labels: hacktoberfest-accepted

#114 CubeSorting using python (https://codeforces.com/contest/1420/problems)
  CodeForces/CF1420A.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#112 Adding new solution for 1431 in python - hacktoberfest
  LeetCode/kids_with_greatest_number_of_candies.py
Labels: hacktoberfest-accepted

#125 New folder for projevt euler has been created and its 10 problems are solved
  .vscode/c_cpp_properties.json
  ProjectEuler/1.cpp
  ProjectEuler/10.cpp
  ProjectEuler/2.cpp
  ProjectEuler/3.cpp
  ProjectEuler/4.cpp
  ProjectEuler/5.cpp
  ProjectEuler/6.cpp
  ProjectEuler/7.cpp
  ProjectEuler/8.cpp
  ProjectEuler/9.cpp
Labels: good first issue, hacktoberfest-accepted

#126 added solution for leetcode prblm #55
  LeetCode/Jump_game.py
Labels: good first issue, hacktoberfest-accepted

#134 Solutions from 11-20 are added
  ProjectEuler/11.cpp
  ProjectEuler/12.cpp
  ProjectEuler/13.cpp
  ProjectEuler/14.cpp
  ProjectEuler/15.cpp
  ProjectEuler/16.cpp
  ProjectEuler/17.cpp
  ProjectEuler/18.cpp
  ProjectEuler/19.cpp
  ProjectEuler/20.cpp
Labels: hacktoberfest-accepted

#132 Create Merge Linked Lists(without new nodes)-hacktoberfest
  Miscellaneous/Merge Linked Lists(without new nodes)
Labels: hacktoberfest-accepted

#131 Merge Two Linked Lists using new nodes-hacktoberfest
  Miscellaneous/Merge Linked Lists
Labels: hacktoberfest-accepted

#130 Added some arrays questions
  Interviewbit/Arrays/Add_One_To_Number.py
  Interviewbit/Arrays/Find_Duplicate_in_Array.py
  Interviewbit/Arrays/Flip.cpp
  Interviewbit/Arrays/Hotel_Bookings_Possible.cpp
  Interviewbit/Arrays/Max_Distance.cpp
  Interviewbit/Arrays/Max_Sum_Contiguous_Subarray.py
  Interviewbit/Arrays/Maximum_Absolute_Difference.py
  Interviewbit/Arrays/Maximum_Consecutive_Gap.py
  Interviewbit/Arrays/Maximum_Unsorted_Subarray.cpp
  Interviewbit/Arrays/Min_Steps_in_Infinite_Grid.cpp
  Interviewbit/Arrays/Noble_Integer.cpp
  Interviewbit/Arrays/Triplets_with_Sum_between_given_range.cpp
  Interviewbit/Arrays/Wave_Array.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#129 added solution for leetcode prblm #72
  LeetCode/Edit_distance.py
Labels: hacktoberfest-accepted

#122 Sum of Round Numbers (https://codeforces.com/contest/1352/problem/A)
  CodeForces/CF1352.cpp
Labels: hacktoberfest-accepted

#136 updated
  Hackerrank/UtopianTree.c
Labels: documentation, hacktoberfest-accepted

#137 ArrayReversal
  CodeChef/CHEFCAKE.cpp
  Hackerrank/1D_Arrays.c
  Hackerrank/ArrayReversal.c
Labels: hacktoberfest-accepted

#139 Create Lisa's_Workbook.c
  Hackerrank/Lisa's_Workbook.c
Labels: hacktoberfest-accepted

#142 added solution for leetcode prblm #20
  LeetCode/Valid_paranthesis.py
Labels: hacktoberfest-accepted

#141 Adding 7 more Arrays questions to the list
  Interviewbit/Arrays/Anti_Diagonals.cpp
  Interviewbit/Arrays/Find_Permutation.cpp
  Interviewbit/Arrays/Kth_Row_of_Pascals_Triangle.cpp
  Interviewbit/Arrays/Largest_Number.py
  Interviewbit/Arrays/Next_Permutation.cpp
  Interviewbit/Arrays/Pascal_Triangle.cpp
  Interviewbit/Arrays/Spiral_Order_Matrix_II.cpp
Labels: hacktoberfest-accepted

#138 Create Append and delete
  Hackerrank/Append and delete
Labels: hacktoberfest-accepted

#143 Added Solution Leetcode Problem #27
  LeetCode/Remove_Element.cpp
Labels: hacktoberfest-accepted

#145 Added solution for Parenthesis Checker
  GeeksForGeeks/Parenthesis_Checker.cpp
Labels: hacktoberfest-accepted

#146 Added Dynamic Programming
  CSES/1633.cpp
  CSES/1634.cpp
  CSES/1635.cpp
  CSES/1636.cpp
  CodeForces/CF1426A.cpp
  CodeForces/CF1426B.cpp
  CodeForces/CF1426C.cpp
  CodeForces/CF1426D.cpp
Labels: hacktoberfest-accepted

#147 Added a new Problem
  GeeksForGeeks/Rank_Permutations.cpp
Labels: hacktoberfest-accepted

#148 Added solutions in hackerrank
  Hackerrank/If_else.py
  Hackerrank/Loops.py
  Hackerrank/Tuples.py
Labels: hacktoberfest-accepted

#150 Create DCANDY.cpp
  CodeChef/DCANDY.cpp
Labels: hacktoberfest-accepted

#153 Added a new GeeksForGeeks Problem
  GeeksForGeeks/Non_Repeating_char.cpp
Labels: hacktoberfest-accepted

#152 Added Dynamic Programming
  CSES/1158.cpp
  CSES/1637.cpp
  CSES/1638.cpp
Labels: hacktoberfest-accepted

#154 Adding 6 array questions & 3 primers
  Interviewbit/Arrays/First_Missing_Integer.cpp
  Interviewbit/Arrays/Merge_Overlapping_Intervals.cpp
  Interviewbit/Arrays/N_division_3_Repeat_Number.cpp
  Interviewbit/Arrays/PRIMER_ARRAY_2D.txt
  Interviewbit/Arrays/PRIMER_ARRAY_BUG.cpp
  Interviewbit/Arrays/PRIMER_ARRAY_IMPL1.txt
  Interviewbit/Arrays/Repeat_and_Missing_Number_Array.py
  Interviewbit/Arrays/Set_Matrix_Zeros.cpp
  Interviewbit/Arrays/Sort_array_with_squares.cpp
Labels: hacktoberfest-accepted

#155 Transition Point in a binary array
  GeeksForGeeks/transitionPoint.cpp
Labels: hacktoberfest-accepted

#157 Added Array Description
  CSES/1746.cpp
Labels: hacktoberfest-accepted

#158 Adding recursion problem solution- Hacktoberfest
  Hackerrank/recursion.java
Labels: good first issue, hacktoberfest-accepted

#159 Added hash maps java program-Hacktoberfest
  Hackerrank/hashmaps.java
Labels: hacktoberfest-accepted

#161 Add files via upload
  HackerEarth/Decode.cpp
  HackerEarth/Password.cpp
Labels: hacktoberfest-accepted

#163 Added few codechef problems
  CodeChef/CHEFSTR1.cpp
  CodeChef/CHFICRM.cpp
  CodeChef/CHFM.cpp
  CodeChef/EOEO.cpp
  CodeChef/PJ10TO2.cpp
  CodeChef/SPELLBOB.cpp
  CodeChef/ZOMCAV.cpp
Labels: hacktoberfest-accepted

#164 Contest 991 added
  CodeForces/991a.cpp
  CodeForces/991b.cpp
  CodeForces/991c.cpp
  CodeForces/991d.cpp
Labels: hacktoberfest-accepted
